/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'victoryw' at '9/16/16 4:43 PM' with Gradle 2.12
 *
 * @author victoryw, @date 9/16/16 4:43 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return false;
    }
}
